CREATE TABLE IF NOT EXISTS Short_F_15_Syllabus (
    `Flt_ID` VARCHAR(8) CHARACTER SET utf8,
    `Flt_Nxt` VARCHAR(8) CHARACTER SET utf8,
    `Flt_Nxt` VARCHAR(5) CHARACTER SET utf8,
    `Flt_Rq` VARCHAR(8) CHARACTER SET utf8,
    `Flt_Rq` VARCHAR(5) CHARACTER SET utf8,
    `Flt_Rq` VARCHAR(5) CHARACTER SET utf8,
    `Ac_Req` VARCHAR(1) CHARACTER SET utf8,
    `MX_Config` VARCHAR(24) CHARACTER SET utf8,
    `Formation_X_ship` NUMERIC(2, 1)
);
INSERT INTO Short_F_15_Syllabus VALUES
    ('TR-1','TR-2','-','-','-','-','Y','cold gun',1.0),
    ('TR-2','TR-3','-','TR-1','-','-','-','cold gun',1.0),
    ('TR-3','TR-4','-','TR-2','-','-','-','cold gun',2.0),
    ('TR-4','TR-5','-','TR-3','-','-','-','cold gun',2.0),
    ('TR-5','TR-6 (P)','-','TR-4','-','-','-','cold gun',2.0),
    ('TR-6 (P)','AHC','-','TR-5','-','-','Y','cold gun',2.0),
    ('AHC','BFM-1','-','TR-6 (P)','-','-','Y','cold gun, 8xBDL50',2.0),
    ('BFM-1','BFM-2','-','AHC','-','-','Y','cold gun, missile config',2.0),
    ('BFM-2','BFM-3','-','BFM-1','-','-','-','cold gun, missile config',2.0),
    ('BFM-3','BFM-4','-','BFM-2','-','-','-','cold gun, missile config',2.0),
    ('BFM-4','BFM-5','-','BFM-3','-','-','-','cold gun, missile config',2.0),
    ('BFM-5','BFM-6','-','BFM-4','-','-','-','cold gun, missile config',2.0),
    ('BFM-6','BFM-7','-','BFM-5','-','-','-','cold gun, missile config',2.0),
    ('BFM-7','BFM-8','-','BFM-6','-','-','Y','cold gun, missile config',2.0),
    ('BFM-8','ACM-1','-','BFM-7','-','-','-','cold gun, missile config',2.0),
    ('ACM-1','SA-1','-','BFM-8','-','-','Y','8xBDL50, 2xAMRAM',1.0),
    ('SA-1','SA-2','-','ACM-1','-','-','Y','hot gun, 2xAMRAM',4.0),
    ('SA-2','LASDT-1','-','SA-1','-','-','Y','hot gun, 2xAMRAM',4.0),
    ('LASDT-1','LASDT-2','-','SA-2','-','-','Y','hot gun, 8xBDL50',4.0),
    ('LASDT-2','SA-3','-','LASDT-1','-','-','-','hot gun, 8xBDL50',4.0),
    ('SA-3','SA-4','-','LASDT-2','-','-','Y','hot gun, 2xAMRAM',2.0),
    ('SA-4','ACM-2','-','SA-3','-','-','-','hot gun, 2xAMRAM',2.0),
    ('ACM-2','ACM-3','-','SA-4','-','-','Y','8xBDL50, 2xAMRAM',4.0),
    ('ACM-3','TI-1','-','ACM-2','-','-','-','8xBDL50, 2xAMRAM',4.0),
    ('TI-1','TI-2','-','ACM-3','-','-','Y','cold gun',1.0),
    ('TI-2','TI-3','-','TI-1','-','-','Y','cold gun',1.0),
    ('TI-3','LASDT-3','NTR-1','TI-2','-','-','Y','cold gun',2.0),
    ('LASDT-3','SA-5','-','TI-3','-','-','Y','hot gun, 8xBDL50',4.0),
    ('SA-5','SA-6','-','LASDT-3','-','-','-','hot gun, 2xAMRAM',2.0),
    ('SA-6','SA-7','-','SA-5','-','-','-','hot gun, 2xAMRAM',2.0),
    ('SA-7','SA-8','-','SA-6','-','-','-','hot gun, 2xAMRAM',2.0),
    ('SA-8','SA-9','-','SA-7','-','-','Y','hot gun, 2xAMRAM',2.0),
    ('SA-9','SA-10','-','SA-8','-','-',NULL,'hot gun, 2xAMRAM',2.0),
    ('SA-10','SAT-1','-','SA-9','-','-','Y','hot gun, 2xAMRAM',2.0),
    ('NTR-1','NTR-2','-','TI-3','-','-','Y','8xBDL50, 4xAMRAM',1.0),
    ('NTR-2','NTI','-','NTR-1','-','-','-','8xBDL50, 4xAMRAM',1.0),
    ('NTI','SAN-1','SAN-3','NTR-2','-','-','Y','cold gun',2.0),
    ('SAN-1','SAN-2','-','NTI','-','-','Y','8xBDL50, 4xAMRAM',2.0),
    ('SAN-2','SAT-1','-','SAN-1','-','-','Y','8xBDL50, 4xAMRAM',4.0),
    ('SAN-3','SAN-4','-','NTI','-','-','Y','8xBDL50, 4xAMRAM',2.0),
    ('SAN-4','SAT-1','-','SAN-3','-','-','Y','8xBDL50, 4xAMRAM',2.0),
    ('SAT-1','SAT-2','-','SA-10','SAN-2','SAN-4','-','hot gun, 4xBDL50',1.0),
    ('SAT-2','-','-','SAT-1','-','-','-','hot gun, 4xBDL50',1.0),
    ('DAAR','NAAR','-','TR-4','-','-','Y','cold gun',1.0),
    ('NAAR','-','-','DAAR','-','-','Y','cold gun',1.0);
